/*  Embedded Systems
    Lab Class 4 - MicroProject 6: Using PWM with the ESP32
    Prof. Guilherme Paim
    IST (Instituto Superior Técnico), INESC-ID, Lisbon
*/

/* Lab Experiment: PWM Signal Analysis with Oscilloscope

   1) Presentation: The students must present their MicroProjects to the professor in the free-time of the Lab class before the deadline.
   Group of Students: 1-2

   2) Report Format (by e-mail): ~ 3-5 pages in PDF
   Student Identification, Introduction, Experiment, Discussion, Conclusion
   Make sure that all questions are very well answered!
   Language: Portuguese/English

   3) Codes (by e-mail): The code must be also delivered in a Zip file.

   Objective:
   Use an oscilloscope to analyze the PWM signal generated by the ESP32, understand how duty cycle and frequency impact the waveform, and explore the behavior under various configurations.

   Documentation: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/ledc.html

   Instructions:
   1. In the report, using the documentation of "ledc PWM", explain the PWM modes, and the PWM configuration options available, and how to calculate the duty cycle.
   2. Test 1: Measure the PWM signal using the oscilloscope while running the provided code. Record the signal’s frequency, duty cycle, and amplitude.
   3. Test 2: Modify the PWM frequency in the `ledc_timer_config` to 6 kHz. Observe and record how this change impacts the waveform.
   4. Test 3: Experiment with increasing the duty cycle by adjusting in a loop Analyze in the oscilloscope the output for these changes. Do not forget to add a small delay of 10ms

   Discussion Questions:
   - How the hardware PWM works ?
   - Why to do not implement in software ?
   - How does the frequency change affect the PWM waveform?
   - What is the maximum resolution of the PWM signal, and how is it affected by the frequency setting?
   - How accurately does the ESP32 produce the desired duty cycles?
   - Why you need to configure the timer?
   - Which outputs can be configured as a PWM ?
   - How many channels you have disponible in ESP32 ?
   - How the difference between the LEDC mode and the MCPWM ?
*/

#include "driver/gpio.h"
#include "driver/ledc.h"
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include <math.h>
#include <stdio.h>

void pwm_init(void) {
	ledc_timer_config_t ledc_timer = {
		.speed_mode = LEDC_LOW_SPEED_MODE,
		.timer_num = LEDC_TIMER_0,
		.duty_resolution = LEDC_TIMER_13_BIT,
		.freq_hz = 5000,
		.clk_cfg = LEDC_AUTO_CLK,
	};
	ledc_timer_config(&ledc_timer);

	ledc_channel_config_t ledc_channel = {
		.speed_mode = LEDC_LOW_SPEED_MODE,
		.channel = LEDC_CHANNEL_0,
		.timer_sel = LEDC_TIMER_0,
		.intr_type = LEDC_INTR_DISABLE,
		.gpio_num = GPIO_NUM_2,
		.duty = 0,
		.hpoint = 0,
	};
	ledc_channel_config(&ledc_channel);
}

void test1() {
	ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, 4095); //2^13 = 8192
	ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);
}

int clamp(int value, int min, int max) {
	if (value < min) {
		return min;
	} else if (value > max) {
		return max;
	} else {
		return value;
	}
}

void test3() {
	int duty_max = 1 << 13;
	int duty_cur = 0;
	int duty_speed = 10;
	bool duty_inc = true;
	while (1) {
		duty_cur = clamp(duty_cur, 0, duty_max);
		ledc_set_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0, duty_cur);
		ledc_update_duty(LEDC_LOW_SPEED_MODE, LEDC_CHANNEL_0);

		if (duty_cur <= 0) {
			duty_inc = true;
		} else if (duty_cur >= duty_max) {
			duty_inc = false;
		}

		if (duty_inc) {
			duty_cur += duty_speed;
		} else {
			duty_cur -= duty_speed;
		}

		vTaskDelay(10 / portTICK_PERIOD_MS);
	}
}

void app_main(void) {
	pwm_init();

	//test1();
	//test3();
}
